name: Linux Build
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
    runs-on: debian:10

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Updates
        run: sudo apt-get update -y

      - name: Install Required Packages
        run: apt-get update && apt-get install git cmake make gcc g++ clang default-libmysqlclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev mariadb-server libace-6.* libace-dev

      - name: Update Compilers
        run: source ./apps/ci/ci-compiler-update.sh

      - name: Check for Submodule Updates
        run: source ./apps/ci/ci-submodule-update.sh

      - name: Build Firelands Project
        run: source ./apps/ci/ci-compile.sh
